### ISSUE TITLE
EL7 support

### ISSUE THREAD

**Issue by skottler** [skottler/zookeeper-rpms#5]
Zookeeper is already available in Fedora, but we've decided to leave it out of EPEL7 because of large dependency tree when packaged 'properly'. There are a few things to do:

* Move and potentially alter the systemd service unit
* Check dependencies
* Verify the configuration against Kafka

**Comment by robinbowes** [comment]
"large dependency tree" - you can say that again.

Is there any news/progress with zookeeper on epel?

**Comment by jim-yefeng** [comment]
build failed on centos7.2 64bits
Start: rpmbuild zookeeper-3.4.6-2.src.rpm
Building target platforms: x86_64
Building for target x86_64
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.iGF1j1
+ umask 022
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ rm -rf zookeeper-3.4.6
+ /usr/bin/gzip -dc /builddir/build/SOURCES/zookeeper-3.4.6.tar.gz
+ /usr/bin/tar -xf -

gzip: /builddir/build/SOURCES/zookeeper-3.4.6.tar.gz: unexpected end of file
/usr/bin/tar: Unexpected EOF in archive
/usr/bin/tar: Unexpected EOF in archive
/usr/bin/tar: Error is not recoverable: exiting now


RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.iGF1j1 (%prep)
    Bad exit status from /var/tmp/rpm-tmp.iGF1j1 (%prep)
ERROR: Exception(zookeeper-3.4.6-2.src.rpm) Config(epel-7-x86_64) 0 minutes 34 seconds
INFO: Results and/or logs in: /var/lib/mock/epel-7-x86_64/result
ERROR: Command failed. See logs for output.

**Comment by skottler** [comment]
This has been addressed in master.
